### ISSUE TITLE
The "main" name of the artist isn't at the first index

### ISSUE THREAD

**Issue by PZeide** [xSardine/AMQ-Artists-DB#5]
The real name of the artist isn't at the first index in the "names" field; example:
`{
  "id": 4782,
  "names": [
    "Hibiki from BEST FRIENDS!",
    "Yoko Hikasa"
  ],
  "members": [],
  "anilistId": 102263
}`

For some songs, a stage name or a name from an anime can be rendered for a totally different anime.
Yoko Hikasa named with her Aikatsu character rather than her real name for a Symphogear insert song: 
![image](https://user-images.githubusercontent.com/43934333/177046059-2e638a80-cafe-4edc-b1b8-96f9718b5b90.png)

**Comment by xSardine** [comment]
ye fixed it before, but forgot to pull data from the right view 🤡 f2d5b3df65e3b5bff9d5e6e7a513348d19647cf8
thanks
